development:
  adapter: postgresql
  encoding: unicode
  database: appname_development
  pool: 5
  username: gambala
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: appname_test
  pool: 5
  username: gambala
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: appname_production
  pool: 5
  username: gambala
  password:
